{% set name = "jsons" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ramonhagenaars/jsons/archive/v{{ version }}.tar.gz
  sha256: 46f0e286edcd1ff46d160af8219db9f2626873225518b80a6c946ada562dec33

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - typish >=1.9.2

test:
  imports:
    - jsons
  requires:
    - pip
    - dataclasses
    - python {{ python_min }}
    - pytest
  source_files:
    - tests
    - test_resources
  commands:
    - pip check
    - pytest --pyargs jsons .

about:
  home: https://github.com/ramonhagenaars/jsons/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Turn Python objects into dicts or (json)strings
  description: Turn Python objects into dicts or (json)strings No changes required to your objects Easily customizable and extendable
  doc_url: https://jsons.readthedocs.io/
  dev_url: https://github.com/ramonhagenaars/jsons/

extra:
  recipe-maintainers:
    - ngodber
